name: Run flake check then build and push Docker images
permissions:
  contents: read
  packages: write
on:
  workflow_call:
    inputs:
      systems:
        description: "The systems for which to add support for. JSON-formatted string."
        required: true
        type: string
      images:
        description: "List of Docker images to use as base name for tags"
        required: false
        type: string
      dockerhub_username:
        description: "Username used to log against the Docker registry"
        required: true
        type: string
      push_images:
        description: "Should the job push the image to Dockerhub?"
        required: true
        type: boolean
    secrets:
      cachix_auth_token:
        description: "Cachix auth token"
        required: true
      codecov_token:
        description: "Codecov token"
        required: true
      dockerhub_token:
        description: "Password or personal access token used to log against the Docker registry"
        required: true
    outputs:
      tags:
        description: "The generated Docker tags"
        value: ${{ jobs.flake_check_and_build_docker_images.outputs.tags }}
      labels:
        description: "The generated Docker labels"
        value: ${{ jobs.flake_check_and_build_docker_images.outputs.labels }}
jobs:
  flake_check_and_build_docker_images:
    strategy:
      matrix:
        system: ${{ fromJson(inputs.systems) }}
    runs-on: ${{ matrix.system == 'aarch64-linux' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: ncps
          authToken: ${{ secrets.cachix_auth_token }}
      - name: Create version file
        shell: bash
        run: |
          if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$ ]]; then
            echo "${{ github.ref_name }}" > nix/packages/ncps/version.txt
          fi
      - name: Flake check
        id: flake-check
        run: nix flake check -L
      - name: Build coverage
        id: build-coverage
        if: github.event.pull_request.head.repo.fork == false
        run: nix build .#ncps.coverage -L
      - name: Upload coverage reports to Codecov
        if: github.event.pull_request.head.repo.fork == false
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.codecov_token }}
          files: result-coverage
      - name: Build the docker image
        shell: bash
        run: |
          set -euo pipefail
          nix build -L .#packages.${{ matrix.system }}.docker
    outputs:
      labels: ${{ steps.meta.outputs.labels }}
      tags: ${{ steps.meta.outputs.tags }}
