name: Build and push Docker images with mult-arch support
on:
  workflow_call:
    inputs:
      systems:
        description: "The systems for which to add support for. JSON-formatted string."
        required: true
        type: string
      images:
        description: "List of Docker images to use as base name for tags"
        required: false
        type: string
      username:
        description: "Username used to log against the Docker registry"
        required: true
        type: string
    secrets:
      password:
        description: "Password or personal access token used to log against the Docker registry"
        required: true
    outputs:
      tags:
        description: "The generated Docker tags"
        value: ${{ jobs.docker-meta.outputs.tags }}
      labels:
        description: "The generated Docker labels"
        value: ${{ jobs.docker-meta.outputs.labels }}
jobs:
  docker-meta:
    runs-on: ubuntu-24.04
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.images }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha
    outputs:
      labels: ${{ steps.meta.outputs.labels }}
      tags: ${{ steps.meta.outputs.tags }}
